
import random

# The roll_dice function simulates the rolling of the dice. It
# creates a 2 dimensional list: each column is a die and each
# row is a throw. The function generates random numbers 1-6
# and puts them in the list.


def roll_dice(num_dice, num_rolls):

    # create a two-dimensional (num_dice by num_rolls) of zeros
    double_list = [[0 for i in range(num_dice)] for j in range(num_rolls)]

    # loop through each row and column, filling it with a random roll
    for roll in range(0, len(double_list)):
        for die in range(0, len(double_list[roll])):
            double_list[roll][die] = (int)(random.random() * 6 + 1)

    return double_list


# This function takes a 2D list (which can be generated by roll_dice)
# and sums the value of all the dice in each row. It returns a 1
# dimensional list with the sum of each throw.
# Example:
# double_list: [[1, 5, 6],[2, 3, 1],[1, 3, 3]]
# sum_of_roll should return: [12, 6, 7]


def sum_of_roll(double_list):
    # Your code here
    sum_list = []
    for roll in double_list:
        sum = 0
        for die in roll:
            sum += die
        sum_list.append(sum)
    return sum_list

# Bonus function! Takes a 2D list and returns
# the number of times a person rolls Yahtzee (all dice have
# the same value). Hint: you may want to create a helper
# function that takes individual rows of the list.


def yahtzee_on_roll(list_of_dice):
    ret_val = False
    for index in range(len(list_of_dice) - 1):
        if list_of_dice[index] == list_of_dice[index + 1]:
            ret_val = True
        else:
            ret_val = False
            break
    return ret_val


def yahtzee(double_list):
    total_yahtzees = 0
    for roll in double_list:
        if yahtzee_on_roll(roll):
            total_yahtzees += 1
    return total_yahtzees


def testEqual(a, b):
    """ Home-rolled version of testEqual """

    if a == b:
        print("Pass")
    else:
        print("Fail")


# To play, yo'd do something like this
# dice = input("How many dice?")
# rolls = input("What is the number of rolls?")
# list = roll_dice(dice, rolls)
# print("Sum of roll:", sum_of_roll(list))


def main():
    """ Cursory test of yahtzee(double_list) """

    print("Testing sum_of_roll...")
    testEqual(sum_of_roll([[4, 5, 2], [6, 2, 1], [4, 4, 4]]), [11, 9, 12])
    testEqual(sum_of_roll([[3, 4, 6], [2, 6, 1], [3, 4, 3]]), [13, 9, 10])
    print("Testing yahtzee...")
    testEqual(yahtzee([[4, 5, 2], [6, 2, 1], [4, 4, 4]]), 1)
    testEqual(yahtzee([[3, 4, 6], [2, 6, 1], [3, 4, 3]]), 0)


if __name__ == "__main__":
    main()
